// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucnmfzwbijcnoviugxzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbm1mendiaWpjbm92aXVneHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTc2NjYsImV4cCI6MjA2MDI3MzY2Nn0.TdLQxM5u4bETcP0lMj_pBr7txP5ZmVPH6NjY9SP1IoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);